[versions]
agp = "8.11.1"
kotlin = "2.2.0"
appVersion = "100"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
hilt = "2.57"
ksp = "2.2.0-2.0.2"
hiltCompiler = "1.2.0"
hiltNavigationCompose = "1.2.0"
moshiConverter = "3.0.0"
moshi = "1.15.2"
pagingCompose = "3.3.6"
retrofit = "3.0.0"
navigationCompose = "2.9.2"
okhttp = "5.1.0"
jetbrainsKotlinJvm = "2.2.0"
kotlinxSerialization = "2.2.0"
kotlinxSerializationJson = "1.9.0"
roomPaging = "2.6.1"
timber = "5.0.1"
retrofitResultAdapterVersion = "1.0.13"
coreSplashscreen = "1.0.1"
preferencesVersion = "1.1.7"
lifecycleProcess = "2.9.2"
appcompat = "1.7.1"
material = "1.12.0"
ktlint = "12.3.0"
accompanistSystemuicontroller = "0.36.0"
glideComposeVerions = "1.0.0-beta01"
glideVersion = "5.0.0-rc01"
roomVersion = "2.7.2"
foundation = "1.8.3"


[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingCompose" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-foundation = {group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
okhttp3 = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
moshi-converter= {group = "com.squareup.retrofit2", name= "converter-moshi", version.ref ="moshiConverter"}
moshi = {group= "com.squareup.moshi", name = "moshi-kotlin", version.ref= "moshi"}
moshi-codegen = {group= "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref= "moshi"}
retrofit-result-adapter = { group = "com.github.skydoves", name = "retrofit-adapters-result", version.ref = "retrofitResultAdapterVersion" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinx-serialization-json =  { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson"}
androidx-dataStore-preferences = {group = "androidx.datastore", name = "datastore-preferences", version.ref = "preferencesVersion"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideComposeVerions" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glideVersion" }
room-ktx = {group= "androidx.room", name = "room-ktx", version.ref = "roomVersion"}
room-compiler = {group= "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
room-paging = {group= "androidx.room", name = "room-paging", version.ref = "roomVersion"}
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
jetbrains-kotlin-serialization = { id ="org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization"}
android-library = { id = "com.android.library", version.ref = "agp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

